include: package:dart_test_tools/analysis_options_package.yaml

analyzer:
  exclude:
    - "**.freezed.dart"
    - "**.g.dart"
    - lib/main.data.dart
    - test/integration/setup/sodium_setup_js.dart
