name: flutter_data_sodium
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://github.com/Skycoder42/flutter_data_extensions

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter_data: ^1.3.4
  hive: ^2.1.0
  meta: ^1.7.0
  sodium: ^1.2.0+2

dev_dependencies:
  build_runner: ^2.1.8
  dart_pre_commit: ^3.0.0
  dart_test_tools: ^3.3.1
  mocktail: ^0.3.0
  test: ^1.20.2
  tuple: ^2.0.0
