name: flutter_data_sodium
description: An extension package to flutter_data that adds End-To-End-Encryption to all requests
version: 1.0.0
homepage: https://github.com/Skycoder42/flutter_data_extensions

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  clock: ^1.1.0
  flutter_data: ^1.3.4
  freezed_annotation: ^1.1.0
  hive: ^2.1.0
  json_annotation: ^4.5.0
  meta: ^1.7.0
  sodium: ^1.2.0+2
  uuid: ^3.0.6

dev_dependencies:
  build_runner: ^2.1.10
  dart_pre_commit: ^3.0.0
  dart_test_tools: ^3.3.1
  freezed: ^1.1.1
  http: ^0.13.4
  js: ^0.6.4
  json_serializable: ^6.2.0
  mocktail: ^0.3.0
  stream_channel: ^2.1.0
  test: ^1.21.1
  tuple: ^2.0.0
  universal_io: ^2.0.4
