name: flutter_data_extensions
repository: https://github.com/Skycoder42/flutter_data_extensions

packages:
  - packages/**

scripts:
  get: dart pub global run melos exec -- dart pub get

  build: dart pub global run melos exec -- dart run build_runner build

  build:watch: dart pub global run melos exec -- dart run build_runner watch

  hooks:init: >-
    bash -c "echo -e
    '#!/bin/sh\nexec dart pub global run melos run hooks:run'
    > .git/hooks/pre-commit
    && chmod a+x .git/hooks/pre-commit"

  hooks:run: dart pub global run melos exec -c1 -- dart run dart_pre_commit
