name: flutter_data_firebase_database
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://github.com/Skycoder42/flutter_data_extensions

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  eventsource: ^0.4.0
  flutter_data: ^1.3.3
  freezed_annotation: ^1.1.0
  hive: ^2.1.0
  http: ^0.13.4
  json_annotation: ^4.4.0
  meta: ^1.7.0
  rxdart: ^0.27.3

dev_dependencies:
  build_runner: ^2.1.8
  dart_pre_commit: ^3.0.0
  dart_test_tools: ^3.3.1
  freezed: ^1.1.1
  json_serializable: ^6.1.5
  mocktail: ^0.3.0
  test: ^1.20.2
  tuple: ^2.0.0
  universal_io: ^2.0.4
