name: flutter_data_firebase_database
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://github.com/Skycoder42/flutter_data_extensions

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter_data: ^1.2.0

dev_dependencies:
  dart_pre_commit: ^3.0.0
  dart_test_tools: ^3.2.1
  test: ^1.20.2
