name: flutter_data_sync
description: An extension package to flutter_data that adds a helper class for offline synchronization
version: 1.0.0
homepage: https://github.com/Skycoder42/flutter_data_extensions

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  bloc_concurrency: ^0.2.0
  flutter_data: 1.3.4
  freezed_annotation: ^1.1.0
  meta: ^1.7.0
  state_machine_bloc: ^0.0.1

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.1.10
  dart_pre_commit: ^3.0.0
  dart_test_tools: ^3.3.1
  freezed: ^1.1.1
  mocktail: ^0.3.0
  test: ^1.21.1
