name: flutter_data_demo
description: Demo app for all the flutter_data extensions
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  dotenv: ^4.0.1
  flutter:
    sdk: flutter
  flutter_data: ^1.3.4
  flutter_data_firebase_database: ^1.0.1
  flutter_data_sodium: ^1.0.0
  flutter_riverpod: ^1.0.3
  freezed_annotation: ^1.1.0
  json_annotation: ^4.5.0
  oauth2: ^2.0.0
  path_provider: ^2.0.9
  sodium_libs: ^1.2.2
  url_launcher: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.10
  json_serializable: ^6.2.0
  freezed: ^1.1.1

dependency_overrides:
  flutter_data_firebase_database:
    path: ../packages/flutter_data_firebase_database
  flutter_data_sodium:
    path: ../packages/flutter_data_sodium

flutter:
  uses-material-design: true
  assets:
    - .env
