name: flutter_data_firebase_database_example
description: A simple command-line application.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter_data: ^1.3.4
  flutter_data_firebase_database:
    path: ..
  json_annotation: ^4.4.0
  meta: ^1.7.0
  riverpod: ^1.0.3

dev_dependencies:
  build_runner: ^2.1.8
  json_serializable: ^6.1.5
