name: CI/CD for flutter_data_sodium

on:
  workflow_dispatch:
  push:
    branches:
      - "*"
    paths:
      - "packages/flutter_data_sodium/**"
      - ".github/workflows/flutter_data_sodium.yaml"
  pull_request:
    branches:
      - "*"
    paths:
      - "packages/flutter_data_sodium/**"
      - ".github/workflows/flutter_data_sodium.yaml"

jobs:
  ci:
    name: CI
    uses: Skycoder42/dart_test_tools/.github/workflows/dart.yml@main
    with:
      workingDirectory: packages/flutter_data_sodium
      buildRunner: true
      publishExclude: >-
        [
          "lib/src/.gitignore"
        ]
      unitTestPaths: test/unit
      coverageExclude: >-
        "**/*.freezed.dart"
        "**/*.g.dart"
      integrationTestPaths: test/integration
      integrationTestSetup: >-
        {
          "linux": "sudo apt-get -qq install libsodium-dev",
          "windows": "dart run tool/download_sodium_windows.dart",
          "macos": "brew install libsodium",
          "web": "dart run tool/download_sodium_web.dart"
        }
