name: CI/CD for flutter_data_firebase_database

on:
  workflow_dispatch:
  push:
    branches:
      - "*"
    paths:
      - "packages/flutter_data_firebase_database/**"
      - ".github/workflows/flutter_data_firebase_database.yaml"
  pull_request:
    branches:
      - "*"
    paths:
      - "packages/flutter_data_firebase_database/**"
      - ".github/workflows/flutter_data_firebase_database.yaml"

jobs:
  ci:
    name: CI
    uses: Skycoder42/dart_test_tools/.github/workflows/dart.yml@main
    with:
      workingDirectory: packages/flutter_data_firebase_database
      buildRunner: true
      unitTestPaths: test/unit
      integrationTestPaths: test/integration
    secrets:
      integrationTestEnvVars: |
        FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }}
